server {
    listen 80;
    
    # Сжатие файлов для скорости
    gzip on;
    gzip_types text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Магия для React Router: если файл не найден, отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов к API
    # Если фронт стучится на /api/users, Nginx перешлет это на backend:5001/api/users
    location /api/ {
        proxy_pass http://backend:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}