# frontend/nginx.conf

server {
    listen 80;
    server_name toolmanager.ru;

    # Редирект с HTTP на HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name toolmanager.ru;

    # Пути к сертификатам (они появятся внутри контейнера после Шага 3)
    ssl_certificate /etc/letsencrypt/live/toolmanager.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toolmanager.ru/privkey.pem;

    # --- Фронтенд (React) ---
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # --- Бэкенд (Проксирование) ---
    # Теперь запросы на /api уходят внутрь Docker-сети на сервис backend:5001
    location /api/ {
        proxy_pass http://backend:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}