export const PERMISSIONS = {
  TOOL_CREATE: 'TOOL_CREATE',
  TOOL_READ: 'TOOL_READ',
  TOOL_UPDATE: 'TOOL_UPDATE',
  TOOL_DELETE: 'TOOL_DELETE',
  TOOL_TRANSFER: 'TOOL_TRANSFER',
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_READ: 'ROLE_READ',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  WAREHOUSE_CREATE: 'WAREHOUSE_CREATE',
  WAREHOUSE_READ: 'WAREHOUSE_READ',
  WAREHOUSE_UPDATE: 'WAREHOUSE_UPDATE',
  WAREHOUSE_DELETE: 'WAREHOUSE_DELETE',
  INVITATION_CREATE: 'INVITATION_CREATE',
  INVITATION_READ: 'INVITATION_READ',
  INVITATION_DELETE: 'INVITATION_DELETE',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
